defprotocol PhoenixTest.Driver do
  @moduledoc false
  def render_page_title(session)
  def render_html(session)
  def click_link(session, text)
  def click_link(session, selector, text)
  def click_button(session, text)
  def click_button(session, selector, text)
  def within(session, selector, fun)
  def fill_in(session, label, attrs)
  def select(session, option, attrs)
  def check(session, label)
  def uncheck(session, label)
  def choose(session, label)
  def submit(session)
  def unwrap(session, fun)
  def open_browser(session)
  def open_browser(session, open_fun)
  def current_path(session)
end
